spring:
  application:
    name: "ManuManager"
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:manutencao_db
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enable: true
    app:
      name: "Api de Manuteção"
      version: 1.0.0
      description: "Api responsável por gerenciar as manutenções de equipamentos"
    metrics:
      tags:
        application: manutencao-app
  metrics:
    enable:
      all: true

h2-server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-exception: false
  address: 0.0.0.0
  port: 8080
