spring:
  application:
    name: "ManuManager"
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost:1521/test;MODE=MSSQLServer
    username: sa
    password:
    driverClassName: org.h2.Driver

h2-server:
  port: 8082

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true